### ISSUE TITLE
problems compiling with gradle

### ISSUE THREAD

**Issue by Checco01** [Sander0542/VelocityUtils#6]
Hi, I tried to modify the plugin to add an extra text string to the / alert command, only when I compiled the plugin it didn't generate the complete .jar file but a DIRTY file.
When I tried to put it on velocity it gave me this error, can you help me?

```
[23:36:16 ERROR]: Couldn't pass ProxyInitializeEvent to velocity-utils
java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
        at org.bstats.MetricsBase.checkRelocation(MetricsBase.java:220) ~[?:?]
        at org.bstats.MetricsBase.<init>(MetricsBase.java:104) ~[?:?]
        at org.bstats.velocity.Metrics.<init>(Metrics.java:84) ~[?:?]
        at org.bstats.velocity.Metrics.<init>(Metrics.java:18) ~[?:?]
        at org.bstats.velocity.Metrics$Factory.make(Metrics.java:49) ~[?:?]
        at com.sanderjochems.minecraft.velocityutils.VelocityUtils.onProxyInitialization(VelocityUtils.java:70) ~[?:?]
        at com.sanderjochems.minecraft.velocityutils.Lmbda$21.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-b8f1df44-bunknown)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-b8f1df44-bunknown)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-b8f1df44-bunknown)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Checco01** [comment]
this is the change I made

```
@Override
    public void execute(SimpleCommand.Invocation invocation) {
        if (invocation.arguments().length < 1) {
            ChatUtil.sendMessage(invocation.source(), String.format("&cUsage: /%s <message>", invocation.alias()));
            return;
        }

        for (Player player : this.server.getAllPlayers()) {
-            ChatUtil.sendMessage(player, String.join(" ", invocation.arguments()));
+            ChatUtil.sendMessage(player,"§c§lALERT §7» §f" + String.join(" ", invocation.arguments()));
        }
    }
```
